#!/usr/bin/env python3
"""Generate a uspecs marketplace from the uspecs source repo.

Reads bin/ and .claude/skills/uspecs-* from the uspecs repo, combines them
with action definitions (scripts/templates/actions/*.yaml) and host-specific
templates, and writes a complete marketplace to the marketplace repo.

Agents:
  claude  -- commands/ + knowledge skills, dispatch: bare `bash softeng.sh`
  augment -- action skills + knowledge skills, dispatch: {PLUGIN_ROOT}/bin/softeng.sh
  codex   -- action skills + knowledge skills, dispatch: {PLUGIN_ROOT}/bin/softeng.sh

Version is read from <uspecs-repo>/version.txt unless --version is provided.

Usage:
    python gen-uspecs-market.py --agent claude|augment|codex --uspecs-repo <uspecs-repo> --marketplace-repo <marketplace-repo> [--version <ver>]

See also: gen-claude.sh, gen-augment.sh (convenience wrappers).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal, cast

import yaml

SCRIPT_DIR: Path = Path(__file__).resolve().parent
TEMPLATES_DIR: Path = SCRIPT_DIR.parent / "templates"
ACTIONS_DIR: Path = TEMPLATES_DIR / "actions"

AgentName = Literal["claude", "augment", "codex"]
OutputKind = Literal["commands", "skills"]


PLUGIN_DESCRIPTION: str = "uspecs framework plugin"
UPSTREAM_URL: str = "https://github.com/untillpro/uspecs"


@dataclass(frozen=True)
class AgentConfig:
    market_name: str
    market_description: str
    action_template: str
    output_kind: OutputKind
    dispatch: str
    host: str
    cli: str


@dataclass
class ActionData:
    action: str
    description: str
    raw_text: str
    options: str = ""


_DISPATCH_PLUGIN_ROOT: str = (
    "Identify the root directory of the plugin (PLUGIN_ROOT) and "
    "run `bash {PLUGIN_ROOT}/bin/softeng.sh action {{action}} [options]`"
)

_DISPATCH_REL_BIN: str = "run `bash ../../bin/softeng.sh action {{action}} [options]`"

AGENT_CONFIGS: dict[AgentName, AgentConfig] = {
    "claude": AgentConfig(
        market_name="uspecs-plugins-claude",
        market_description="uspecs framework plugins for Claude Code",
        action_template="action-command-claude.md",
        output_kind="commands",
        dispatch="run `bash softeng.sh action {{action}} [options]`",
        host="Claude Code",
        cli="claude",
    ),
    "augment": AgentConfig(
        market_name="uspecs-plugins-augment",
        market_description="uspecs framework plugins for Augment Code",
        action_template="action-skill-generic.md",
        output_kind="skills",
        dispatch=_DISPATCH_PLUGIN_ROOT,
        host="Augment Code",
        cli="augment",
    ),
    "codex": AgentConfig(
        market_name="uspecs-plugins-codex",
        market_description="uspecs framework plugins for Codex",
        action_template="action-skill-generic.md",
        output_kind="skills",
        dispatch=_DISPATCH_REL_BIN,
        host="Codex",
        cli="codex",
    ),
}


FEATURES_REL: str = "uspecs/specs/prod/softeng"

# Marketplace repo guard: marketplace.json `name` must match this to be
# recognised as previously generated by us. Matches `uspecs-plugins-claude`,
# `uspecs-dev-plugins-augment`, etc.
_MARKETPLACE_NAME_PATTERN: re.Pattern[str] = re.compile(r"^uspecs.*plugin")


def validate_marketplace_repo(output: Path) -> None:
    """Refuse to wipe --marketplace-repo unless it looks safe.

    Safe means one of:
      - The path does not exist yet (will be created empty).
      - The directory is empty apart from .git.
      - .claude-plugin/marketplace.json parses and its `name` matches
        the marketplace name pattern (proof of prior generation).
    """
    if not output.exists():
        return
    if not output.is_dir():
        print(f"error: --marketplace-repo {output} is not a directory", file=sys.stderr)
        sys.exit(1)

    mf: Path = output / ".claude-plugin" / "marketplace.json"
    if mf.is_file():
        try:
            parsed: object = json.loads(mf.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(
                f"error: --marketplace-repo {output}: marketplace.json is not valid JSON: {e}",
                file=sys.stderr,
            )
            sys.exit(1)
        if not isinstance(parsed, dict):
            print(
                f"error: --marketplace-repo {output}: marketplace.json is not a JSON object",
                file=sys.stderr,
            )
            sys.exit(1)
        data: dict[str, object] = cast("dict[str, object]", parsed)
        name_value: object = data.get("name", "")
        name: str = name_value if isinstance(name_value, str) else ""
        if not _MARKETPLACE_NAME_PATTERN.match(name):
            print(
                f"error: --marketplace-repo {output}: marketplace.json name "
                f"{name!r} does not match {_MARKETPLACE_NAME_PATTERN.pattern!r}; "
                f"refusing to wipe",
                file=sys.stderr,
            )
            sys.exit(1)
        return

    children: list[str] = sorted(c.name for c in output.iterdir() if c.name != ".git")
    if children:
        print(
            f"error: --marketplace-repo {output}: not a recognised marketplace "
            f"and not empty (found: {children}); refusing to wipe",
            file=sys.stderr,
        )
        sys.exit(1)


# Characters that require quoting in YAML plain scalars (subset relevant to
# frontmatter values).  Per YAML 1.2.2 section 7.3.3: plain scalars must
# never contain ": " or " #".
_YAML_PLAIN_FORBIDDEN: list[str] = [": ", " #"]


def validate_skill_frontmatter(skills_dir: Path) -> None:
    """Validate that SKILL.md frontmatter values do not contain ': ' or ' #'.

    These character sequences are forbidden in YAML plain (unquoted) scalars
    and cause parse failures in strict YAML parsers (e.g. Codex).
    """
    import re

    for skill_md in sorted(skills_dir.rglob("SKILL.md")):
        text: str = skill_md.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            continue
        end: int = text.find("\n---", 1)
        if end == -1:
            print(
                f"error: {skill_md}: frontmatter is missing a closing '---' "
                f"terminator.",
                file=sys.stderr,
            )
            sys.exit(1)
        frontmatter: str = text[4:end]
        for line_no, line in enumerate(frontmatter.split("\n"), start=2):
            # Match "key: value" lines (skip continuation lines, blank lines)
            m = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):[ ](.*)", line)
            if not m:
                continue
            key: str = m.group(1)
            value: str = m.group(2)
            # Skip quoted values
            if (value.startswith("'") and value.endswith("'")) or (
                value.startswith('"') and value.endswith('"')
            ):
                continue
            for seq in _YAML_PLAIN_FORBIDDEN:
                if seq in value:
                    print(
                        f"error: {skill_md}:{line_no}: frontmatter field "
                        f"'{key}' contains '{seq}' which is invalid in "
                        f"unquoted YAML. Quote the value.",
                        file=sys.stderr,
                    )
                    sys.exit(1)


def read_feature_description(source: Path, action: str) -> str:
    """Read the Feature title from {source}/uspecs/specs/prod/softeng/{action}.feature."""
    feature_path: Path = source / FEATURES_REL / f"{action}.feature"
    if not feature_path.is_file():
        print(f"error: feature file not found: {feature_path}", file=sys.stderr)
        sys.exit(1)
    first_line: str = feature_path.read_text(encoding="utf-8").split("\n", 1)[0]
    prefix: str = "Feature: "
    if not first_line.startswith(prefix):
        print(
            f"error: expected 'Feature: ...' in {feature_path}, got: {first_line}",
            file=sys.stderr,
        )
        sys.exit(1)
    description: str = first_line[len(prefix) :].strip()
    for seq in _YAML_PLAIN_FORBIDDEN:
        if seq in description:
            print(
                f"error: {feature_path}: feature title contains '{seq}' "
                f"which is invalid in unquoted YAML. Fix the .feature file.",
                file=sys.stderr,
            )
            sys.exit(1)
    return description


def load_actions(source: Path) -> list[ActionData]:
    """Load action YAML files; read descriptions from feature files in source repo."""
    actions: list[ActionData] = []
    for path in sorted(ACTIONS_DIR.glob("*.yaml")):
        with open(path, encoding="utf-8") as f:
            data: dict[str, str] = yaml.safe_load(f)
        action_name: str = data["action"]
        actions.append(
            ActionData(
                action=action_name,
                description=read_feature_description(source, action_name),
                raw_text=data["raw_text"],
                options=data.get("options", ""),
            )
        )
    return actions


def render_dispatch(dispatch_template: str, action_name: str) -> str:
    return dispatch_template.replace("{{action}}", action_name)


def render_action_file(
    template_text: str, action: ActionData, dispatch_line: str
) -> str:
    """Render a command .md or SKILL.md from template + action data."""
    raw_text: str = action.raw_text.rstrip("\n")
    raw_text_with_dispatch: str = raw_text.replace("{{dispatch}}", dispatch_line)

    options_line: str = f"Options: {action.options}" if action.options else ""

    result: str = template_text
    result = result.replace("{{action}}", action.action)
    result = result.replace("{{description}}", action.description)
    result = result.replace("{{raw_text_with_dispatch}}", raw_text_with_dispatch)
    result = result.replace("{{options_line}}", options_line)

    # Clean up trailing blank lines from empty options
    while result.endswith("\n\n\n"):
        result = result[:-1]

    return result


def is_dev_version(version: str) -> bool:
    """Dev builds have a `-dev+` token (build metadata after pre-release `dev`)."""
    return "-dev+" in version


def dev_market_name(stable_name: str) -> str:
    """Insert `-dev` after the project token: uspecs-plugins-claude -> uspecs-dev-plugins-claude."""
    prefix: str = "uspecs-"
    if not stable_name.startswith(prefix):
        return stable_name
    return f"uspecs-dev-{stable_name[len(prefix):]}"


def resolve_names(config: AgentConfig, version: str) -> tuple[str, str]:
    """Return (market_name, plugin_name) adjusted for dev builds."""
    if is_dev_version(version):
        return dev_market_name(config.market_name), "uspecs-dev"
    return config.market_name, "uspecs"


def resolve_description(config: AgentConfig, version: str) -> str:
    """Return marketplace description, with a dev-build suffix for dev versions."""
    if is_dev_version(version):
        return f"{config.market_description} (development build)"
    return config.market_description


def get_upstream_commit(source: Path) -> str:
    """Return source repo HEAD SHA, with `-dirty` if working tree is dirty."""
    try:
        sha: str = subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
    try:
        status: str = subprocess.check_output(
            ["git", "-C", str(source), "status", "--porcelain"],
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        status = ""
    return f"{sha}-dirty" if status.strip() else sha


def render_marketplace(config: AgentConfig, version: str, plugin_name: str) -> str:
    """Render marketplace.json from template.

    Plugin structure (skills, commands, bin) is auto-discovered by the host
    from the plugin source directory -- no need to list them here.
    """
    market_name, _ = resolve_names(config, version)
    tpl_path: Path = TEMPLATES_DIR / "marketplace.json"
    result: str = tpl_path.read_text(encoding="utf-8")
    result = result.replace("{{market_name}}", market_name)
    result = result.replace(
        "{{market_description}}", resolve_description(config, version)
    )
    result = result.replace("{{version}}", version)
    result = result.replace("{{plugin_name}}", plugin_name)
    return result


def render_plugin_json(version: str, plugin_name: str) -> str:
    """Render plugin.json from template."""
    tpl_path: Path = TEMPLATES_DIR / "plugin.json"
    with open(tpl_path, encoding="utf-8") as f:
        parsed: object = json.load(f)
    if not isinstance(parsed, dict):
        print(
            f"error: plugin.json template is not a JSON object: {tpl_path}",
            file=sys.stderr,
        )
        sys.exit(1)
    plugin: dict[str, object] = cast("dict[str, object]", parsed)

    plugin["name"] = plugin_name
    plugin["description"] = PLUGIN_DESCRIPTION
    plugin["version"] = version

    return json.dumps(plugin, indent=2, ensure_ascii=False) + "\n"


def render_install_block(
    config: AgentConfig, market_name: str, plugin_name: str
) -> str:
    """Per-agent install commands (matches scripts/INSTALL.md format)."""
    # Derive repo path from market_name (already dev-adjusted when needed)
    repo_path: str = f"uspecs/{market_name}"
    return (
        "```sh\n"
        f"{config.cli} plugin marketplace add {repo_path}\n"
        f"{config.cli} plugin install {plugin_name}@{market_name}\n"
        "```"
    )


def render_readme(
    config: AgentConfig,
    version: str,
    market_name: str,
    plugin_name: str,
    upstream_commit: str,
    generated_at: str,
) -> str:
    """Render README.md from template."""
    tpl_path: Path = TEMPLATES_DIR / "README.md.tpl"
    is_dev: bool = is_dev_version(version)
    install_block: str = render_install_block(config, market_name, plugin_name)
    result: str = tpl_path.read_text(encoding="utf-8")
    result = result.replace("{{market_name}}", market_name)
    if is_dev:
        banner: str = (
            f"> WARNING: Development build. For stable use, install "
            f"`{config.market_name}` instead."
        )
        result = result.replace("{{is_dev_banner}}", banner)
    else:
        # Drop the placeholder line and its trailing blank line entirely.
        result = result.replace("{{is_dev_banner}}\n\n", "")
    result = result.replace("{{host}}", config.host)
    result = result.replace("{{version}}", version)
    result = result.replace("{{generated_at}}", generated_at)
    result = result.replace("{{upstream_url}}", UPSTREAM_URL)
    result = result.replace("{{upstream_commit}}", upstream_commit)
    result = result.replace("{{install_block}}", install_block)
    return result


def main() -> None:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="Generate a uspecs marketplace.",
    )
    parser.add_argument("--agent", required=True, choices=AGENT_CONFIGS.keys())
    parser.add_argument(
        "--uspecs-repo", required=True, help="Path to uspecs source repo"
    )
    parser.add_argument(
        "--marketplace-repo", required=True, help="Path to output marketplace repo"
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Version string (default: read from uspecs-repo/version.txt)",
    )
    args: argparse.Namespace = parser.parse_args()

    config: AgentConfig = AGENT_CONFIGS[args.agent]
    source: Path = Path(args.uspecs_repo)
    output: Path = Path(args.marketplace_repo)

    # Validate the destructive arg first to fail fast on unsafe wipe targets.
    validate_marketplace_repo(output)

    if not source.is_dir():
        print(f"error: --uspecs-repo directory not found: {source}", file=sys.stderr)
        sys.exit(1)

    version: str = args.version or ""
    if not version:
        version_file: Path = source / "version.txt"
        if version_file.is_file():
            version = version_file.read_text(encoding="utf-8").strip()
        else:
            print(
                f"error: no --version and no version.txt in --uspecs-repo {source}",
                file=sys.stderr,
            )
            sys.exit(1)

    market_name, plugin_name = resolve_names(config, version)
    upstream_commit: str = get_upstream_commit(source)
    generated_at: str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Drop everything in --marketplace-repo except .git (already validated above).
    # Fail fast and loud if any entry cannot be removed (locked file, permissions, ...).
    output.mkdir(parents=True, exist_ok=True)
    for child in output.iterdir():
        if child.name == ".git":
            continue
        try:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
        except OSError as e:
            print(
                f"error: could not remove {child}: {e}",
                file=sys.stderr,
            )
            sys.exit(1)

    plugin_dir: Path = output / "uspecs"
    plugin_dir.mkdir()
    root_claude: Path = output / ".claude-plugin"
    readme_path: Path = output / "README.md"

    # Copy LICENSE from --uspecs-repo
    license_src: Path = source / "LICENSE"
    if not license_src.is_file():
        print(
            f"error: LICENSE not found in --uspecs-repo: {license_src}",
            file=sys.stderr,
        )
        sys.exit(1)
    shutil.copy2(license_src, output / "LICENSE")

    # Copy bin/
    shutil.copytree(source / "bin", plugin_dir / "bin")

    # Copy knowledge skills (uspecs-* only, from .claude/skills/)
    src_skills: Path = source / ".claude" / "skills"

    # Validate knowledge skill frontmatter at source
    validate_skill_frontmatter(src_skills)

    dst_skills: Path = plugin_dir / "skills"
    dst_skills.mkdir()
    for skill_dir in sorted(src_skills.iterdir()):
        if skill_dir.is_dir() and skill_dir.name.startswith("uspecs-"):
            shutil.copytree(skill_dir, dst_skills / skill_dir.name)

    # Load template and actions
    tpl_path: Path = TEMPLATES_DIR / config.action_template
    template_text: str = tpl_path.read_text(encoding="utf-8")
    actions: list[ActionData] = load_actions(source)

    commands_dir: str | None = None
    if config.output_kind == "commands":
        # Claude: generate commands/<action>.md
        commands_dir = "commands"
        cmd_dir: Path = plugin_dir / commands_dir
        cmd_dir.mkdir()
        for action in actions:
            dispatch: str = render_dispatch(config.dispatch, action.action)
            content: str = render_action_file(template_text, action, dispatch)
            (cmd_dir / f"{action.action}.md").write_text(content, encoding="utf-8")
    else:
        # Augment/Codex: generate skills/<action>/SKILL.md
        for action in actions:
            dispatch = render_dispatch(config.dispatch, action.action)
            content = render_action_file(template_text, action, dispatch)
            action_skill_dir: Path = dst_skills / action.action
            action_skill_dir.mkdir(exist_ok=True)
            (action_skill_dir / "SKILL.md").write_text(content, encoding="utf-8")

    # Generate .claude-plugin/marketplace.json (at repo root)
    root_claude.mkdir()
    manifest: str = render_marketplace(config, version, plugin_name)
    (root_claude / "marketplace.json").write_text(manifest, encoding="utf-8")

    # Generate plugin.json inside the plugin directory
    plugin_claude_dir: Path = plugin_dir / ".claude-plugin"
    plugin_claude_dir.mkdir()
    plugin_json: str = render_plugin_json(version, plugin_name)
    (plugin_claude_dir / "plugin.json").write_text(plugin_json, encoding="utf-8")

    # Generate README.md at repo root
    readme: str = render_readme(
        config, version, market_name, plugin_name, upstream_commit, generated_at
    )
    readme_path.write_text(readme, encoding="utf-8")

    print(f"Generated {market_name} at {output}")


if __name__ == "__main__":
    main()
