#!/usr/bin/env python3
"""Generate a uspecs marketplace from the uspecs source repo.

Reads bin/ and .claude/skills/uspecs-* from the uspecs repo, combines them
with action definitions (scripts/templates/actions/*.yaml) and host-specific
templates, and writes a complete marketplace to the marketplace repo.

Agents:
  claude  -- commands/ + knowledge skills, dispatch: bare `softeng.sh`
  augment -- action skills + knowledge skills, dispatch: {PLUGIN_ROOT}/bin/softeng.sh
  codex   -- action skills + knowledge skills, dispatch: ../../bin/softeng.sh (relative to the skill folder)

Version must be supplied via --version (this script does not read version.txt).

Usage:
    python gen-uspecs-market.py --agent claude|augment|codex --uspecs-repo <uspecs-repo> --marketplace-repo <marketplace-repo> --version <ver>
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal, cast

import yaml

SCRIPT_DIR: Path = Path(__file__).resolve().parent
TEMPLATES_DIR: Path = SCRIPT_DIR.parent / "templates"
ACTIONS_DIR: Path = TEMPLATES_DIR / "actions"

AgentName = Literal["claude", "augment", "codex"]
OutputKind = Literal["commands", "skills"]


PLUGIN_DESCRIPTION: str = "uspecs framework plugin"
UPSTREAM_URL: str = "https://github.com/untillpro/uspecs"


@dataclass(frozen=True)
class AgentConfig:
    market_name: str
    market_description: str
    action_template: str
    output_kind: OutputKind
    dispatch: str
    host: str
    cli: str
    install_verb: str
    marketplace_update_verb: str


@dataclass
class ActionData:
    action: str
    description: str
    raw_text: str
    options: str = ""


_DISPATCH_PLUGIN_ROOT: str = (
    "Identify the root directory of the plugin (PLUGIN_ROOT), "
    "run `bash {PLUGIN_ROOT}/bin/softeng.sh action {{action}} [options]`"
)

_DISPATCH_REL_BIN: str = (
    "set cwd to project root and run `bash {SKILL_FOLDER}/../../bin/softeng.sh action {{action}} [options]` "
)

_DISPATCH_DIRECT: str = "run `bash softeng.sh action {{action}} [options]`"

AGENT_CONFIGS: dict[AgentName, AgentConfig] = {
    "claude": AgentConfig(
        market_name="uspecs-plugins-claude",
        market_description="uspecs framework plugins for Claude Code",
        action_template="action-command-claude.md",
        output_kind="commands",
        dispatch=_DISPATCH_DIRECT,
        host="Claude Code",
        cli="claude",
        install_verb="install",
        marketplace_update_verb="update",
    ),
    "augment": AgentConfig(
        market_name="uspecs-plugins-augment",
        market_description="uspecs framework plugins for Augment Code",
        action_template="action-skill-generic.md",
        output_kind="skills",
        dispatch=_DISPATCH_PLUGIN_ROOT,
        host="Augment Code",
        cli="auggie",
        install_verb="install",
        marketplace_update_verb="update",
    ),
    "codex": AgentConfig(
        market_name="uspecs-plugins-codex",
        market_description="uspecs framework plugins for Codex",
        action_template="action-skill-generic.md",
        output_kind="skills",
        dispatch=_DISPATCH_REL_BIN,
        host="Codex",
        cli="codex",
        install_verb="add",
        marketplace_update_verb="upgrade",
    ),
}


FEATURES_REL: str = "uspecs/specs/prod/softeng"

# Marketplace repo guard: marketplace.json `name` must match this to be
# recognised as previously generated by us. Matches `uspecs-plugins-claude`,
# `uspecs-dev-plugins-augment`, etc.
_MARKETPLACE_NAME_PATTERN: re.Pattern[str] = re.compile(r"^uspecs.*plugin")

# Bootstrap files tolerated in an otherwise-empty destination repo (e.g. a
# freshly created GitHub repo initialised with a README). Anything outside
# this set blocks the wipe.
_BOOTSTRAP_ALLOWED: frozenset[str] = frozenset({"README.md", ".gitignore", "LICENSE"})


def validate_marketplace_repo(output: Path) -> None:
    """Refuse to wipe --marketplace-repo unless it looks safe.

    Safe means one of:
      - The path does not exist yet (will be created empty).
      - The directory contains only .git and/or bootstrap files
        (README.md, .gitignore, LICENSE).
      - .claude-plugin/marketplace.json parses and its `name` matches
        the marketplace name pattern (proof of prior generation).
    """
    if not output.exists():
        return
    if not output.is_dir():
        print(f"error: --marketplace-repo {output} is not a directory", file=sys.stderr)
        sys.exit(1)

    mf: Path = output / ".claude-plugin" / "marketplace.json"
    if mf.is_file():
        try:
            parsed: object = json.loads(mf.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(
                f"error: --marketplace-repo {output}: marketplace.json is not valid JSON: {e}",
                file=sys.stderr,
            )
            sys.exit(1)
        if not isinstance(parsed, dict):
            print(
                f"error: --marketplace-repo {output}: marketplace.json is not a JSON object",
                file=sys.stderr,
            )
            sys.exit(1)
        data: dict[str, object] = cast("dict[str, object]", parsed)
        name_value: object = data.get("name", "")
        name: str = name_value if isinstance(name_value, str) else ""
        if not _MARKETPLACE_NAME_PATTERN.match(name):
            print(
                f"error: --marketplace-repo {output}: marketplace.json name "
                f"{name!r} does not match {_MARKETPLACE_NAME_PATTERN.pattern!r}; "
                f"refusing to wipe",
                file=sys.stderr,
            )
            sys.exit(1)
        return

    extras: list[str] = sorted(
        c.name
        for c in output.iterdir()
        if c.name != ".git" and c.name not in _BOOTSTRAP_ALLOWED
    )
    if extras:
        print(
            f"error: --marketplace-repo {output}: not a recognised marketplace "
            f"and contains non-bootstrap files (found: {extras}); refusing to wipe",
            file=sys.stderr,
        )
        sys.exit(1)


# Characters that require quoting in YAML plain scalars (subset relevant to
# frontmatter values).  Per YAML 1.2.2 section 7.3.3: plain scalars must
# never contain ": " or " #".
_YAML_PLAIN_FORBIDDEN: list[str] = [": ", " #"]


def validate_skill_frontmatter(skills_dir: Path) -> None:
    """Validate that SKILL.md frontmatter values do not contain ': ' or ' #'.

    These character sequences are forbidden in YAML plain (unquoted) scalars
    and cause parse failures in strict YAML parsers (e.g. Codex).
    """
    import re

    for skill_md in sorted(skills_dir.rglob("SKILL.md")):
        text: str = skill_md.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            continue
        end: int = text.find("\n---", 1)
        if end == -1:
            print(
                f"error: {skill_md}: frontmatter is missing a closing '---' "
                f"terminator.",
                file=sys.stderr,
            )
            sys.exit(1)
        frontmatter: str = text[4:end]
        for line_no, line in enumerate(frontmatter.split("\n"), start=2):
            # Match "key: value" lines (skip continuation lines, blank lines)
            m = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):[ ](.*)", line)
            if not m:
                continue
            key: str = m.group(1)
            value: str = m.group(2)
            # Skip quoted values
            if (value.startswith("'") and value.endswith("'")) or (
                value.startswith('"') and value.endswith('"')
            ):
                continue
            for seq in _YAML_PLAIN_FORBIDDEN:
                if seq in value:
                    print(
                        f"error: {skill_md}:{line_no}: frontmatter field "
                        f"'{key}' contains '{seq}' which is invalid in "
                        f"unquoted YAML. Quote the value.",
                        file=sys.stderr,
                    )
                    sys.exit(1)


def read_feature_description(source: Path, action: str) -> str:
    """Read the Feature title from {source}/uspecs/specs/prod/softeng/{action}.feature."""
    feature_path: Path = source / FEATURES_REL / f"{action}.feature"
    if not feature_path.is_file():
        print(f"error: feature file not found: {feature_path}", file=sys.stderr)
        sys.exit(1)
    first_line: str = feature_path.read_text(encoding="utf-8").split("\n", 1)[0]
    prefix: str = "Feature: "
    if not first_line.startswith(prefix):
        print(
            f"error: expected 'Feature: ...' in {feature_path}, got: {first_line}",
            file=sys.stderr,
        )
        sys.exit(1)
    description: str = first_line[len(prefix) :].strip()
    for seq in _YAML_PLAIN_FORBIDDEN:
        if seq in description:
            print(
                f"error: {feature_path}: feature title contains '{seq}' "
                f"which is invalid in unquoted YAML. Fix the .feature file.",
                file=sys.stderr,
            )
            sys.exit(1)
    return description


def _resolve_bash() -> str:
    """Locate a bash executable, skipping the Windows System32 WSL launcher.

    On Windows, ``C:\\Windows\\System32\\bash.exe`` is the WSL launcher and
    fails when WSL/Hyper-V is unavailable. Walk PATH and return the first
    ``bash`` that is not under System32; fall back to Git Bash on Windows.
    """
    is_windows: bool = os.name == "nt"
    exts: list[str] = [".exe", ""] if is_windows else [""]
    for raw_dir in os.environ.get("PATH", os.defpath).split(os.pathsep):
        if not raw_dir:
            continue
        d: Path = Path(raw_dir)
        if is_windows and d.name.lower() == "system32":
            continue
        for ext in exts:
            cand: Path = d / f"bash{ext}"
            if cand.is_file():
                return str(cand)
    if is_windows:
        git_bash: Path = Path("C:/Program Files/Git/usr/bin/bash.exe")
        if git_bash.is_file():
            return str(git_bash)
    return "bash"


def read_action_options(source: Path, action: str) -> str:
    """Read an action's rendered options from `softeng meta options <action>`."""
    softeng_path: Path = source / "bin" / "softeng.sh"
    result: subprocess.CompletedProcess[str] = subprocess.run(
        [_resolve_bash(), str(softeng_path), "meta", "options", action],
        cwd=source,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        print(
            f"error: failed to read options for action {action!r} from {softeng_path}: "
            f"{result.stderr.strip() or result.stdout.strip()}",
            file=sys.stderr,
        )
        sys.exit(1)

    line: str = result.stdout.rstrip("\n")
    prefix: str = "Options: "
    if not line.startswith(prefix):
        print(
            f"error: unexpected options output for action {action!r}: {line!r}",
            file=sys.stderr,
        )
        sys.exit(1)
    return line[len(prefix) :]


def load_actions(source: Path) -> list[ActionData]:
    """Load action YAML files; read descriptions from feature files in source repo.

    Each action YAML must specify exactly one of `raw_text` or `file`. When
    `file` is set, the body is read from `ACTIONS_DIR / data["file"]`.
    """
    actions: list[ActionData] = []
    for path in sorted(ACTIONS_DIR.glob("*.yaml")):
        with open(path, encoding="utf-8") as f:
            data: dict[str, str] = yaml.safe_load(f)
        action_name: str = data["action"]
        has_raw: bool = "raw_text" in data
        has_file: bool = "file" in data
        if has_raw == has_file:
            print(
                f"error: {path}: action YAML must specify exactly one of "
                f"`raw_text` or `file`",
                file=sys.stderr,
            )
            sys.exit(1)
        if has_file:
            body_path: Path = ACTIONS_DIR / data["file"]
            if not body_path.is_file():
                print(
                    f"error: {path}: `file` references missing body file: "
                    f"{body_path}",
                    file=sys.stderr,
                )
                sys.exit(1)
            raw_text: str = body_path.read_text(encoding="utf-8")
        else:
            raw_text = data["raw_text"]
        actions.append(
            ActionData(
                action=action_name,
                description=read_feature_description(source, action_name),
                raw_text=raw_text,
                options="" if has_file else read_action_options(source, action_name),
            )
        )
    return actions


def render_dispatch(dispatch_template: str, action_name: str) -> str:
    return dispatch_template.replace("{{action}}", action_name)


def render_action_file(
    template_text: str, action: ActionData, dispatch_line: str
) -> str:
    """Render a command .md or SKILL.md from template + action data.

    Placeholder substitution is a no-op when the placeholder is absent from
    the body, so bodies sourced via the action YAML `file:` field (which have
    no `{{dispatch}}`) are embedded as-is.
    """
    raw_text: str = action.raw_text.rstrip("\n")
    raw_text_with_dispatch: str = raw_text.replace("{{dispatch}}", dispatch_line)

    options_line: str = (
        f"Possible options: {action.options}\n\n"
        "Do not pass options that are not implied by the instructions above "
        "or explicitly requested by the user."
        if action.options
        else ""
    )

    result: str = template_text
    result = result.replace("{{action}}", action.action)
    result = result.replace("{{description}}", action.description)
    result = result.replace("{{raw_text_with_dispatch}}", raw_text_with_dispatch)
    result = result.replace("{{options_line}}", options_line)

    # Clean up trailing blank lines from empty options
    while result.endswith("\n\n\n"):
        result = result[:-1]

    return result


def is_dev_version(version: str) -> bool:
    """Dev builds have a `-dev+` token (build metadata after pre-release `dev`)."""
    return "-dev+" in version


def dev_market_name(stable_name: str) -> str:
    """Insert `-dev` after the project token: uspecs-plugins-claude -> uspecs-dev-plugins-claude."""
    prefix: str = "uspecs-"
    if not stable_name.startswith(prefix):
        return stable_name
    return f"uspecs-dev-{stable_name[len(prefix):]}"


def resolve_names(config: AgentConfig, version: str) -> tuple[str, str]:
    """Return (market_name, plugin_name) adjusted for dev builds."""
    if is_dev_version(version):
        return dev_market_name(config.market_name), "uspecs-dev"
    return config.market_name, "uspecs"


def resolve_description(config: AgentConfig, version: str) -> str:
    """Return marketplace description, with a dev-build suffix for dev versions."""
    if is_dev_version(version):
        return f"{config.market_description} (development build)"
    return config.market_description


def resolve_plugin_description(version: str) -> str:
    """Return plugin description, with a dev-build suffix for dev versions."""
    if is_dev_version(version):
        return f"{PLUGIN_DESCRIPTION} (development build)"
    return PLUGIN_DESCRIPTION


def get_upstream_commit(source: Path) -> str:
    """Return source repo HEAD SHA, with `-dirty` if working tree is dirty."""
    try:
        sha: str = subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
    try:
        status: str = subprocess.check_output(
            ["git", "-C", str(source), "status", "--porcelain"],
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        status = ""
    return f"{sha}-dirty" if status.strip() else sha


def render_marketplace(config: AgentConfig, version: str, plugin_name: str) -> str:
    """Render marketplace.json from template.

    Plugin structure (skills, commands, bin) is auto-discovered by the host
    from the plugin source directory -- no need to list them here.
    """
    market_name, _ = resolve_names(config, version)
    tpl_path: Path = TEMPLATES_DIR / "marketplace.json"
    result: str = tpl_path.read_text(encoding="utf-8")
    result = result.replace("{{market_name}}", market_name)
    result = result.replace(
        "{{market_description}}", resolve_description(config, version)
    )
    result = result.replace("{{version}}", version)
    result = result.replace("{{plugin_name}}", plugin_name)
    return result


def render_plugin_json(version: str, plugin_name: str) -> str:
    """Render plugin.json from template."""
    tpl_path: Path = TEMPLATES_DIR / "plugin.json"
    with open(tpl_path, encoding="utf-8") as f:
        parsed: object = json.load(f)
    if not isinstance(parsed, dict):
        print(
            f"error: plugin.json template is not a JSON object: {tpl_path}",
            file=sys.stderr,
        )
        sys.exit(1)
    plugin: dict[str, object] = cast("dict[str, object]", parsed)

    plugin["name"] = plugin_name
    plugin["description"] = resolve_plugin_description(version)
    plugin["version"] = version

    return json.dumps(plugin, indent=2, ensure_ascii=False) + "\n"


def render_install_block(
    config: AgentConfig, market_name: str, plugin_name: str
) -> str:
    """Per-agent install commands."""
    # Derive repo path from market_name (already dev-adjusted when needed)
    repo_path: str = f"uspecs/{market_name}"
    return (
        "```sh\n"
        f"{config.cli} plugin marketplace add {repo_path}\n"
        f"{config.cli} plugin {config.install_verb} {plugin_name}@{market_name}\n"
        "```"
    )


def render_readme(
    config: AgentConfig,
    version: str,
    market_name: str,
    plugin_name: str,
    upstream_commit: str,
    generated_at: str,
) -> str:
    """Render README.md from template."""
    tpl_path: Path = TEMPLATES_DIR / "README.md.tpl"
    is_dev: bool = is_dev_version(version)
    install_block: str = render_install_block(config, market_name, plugin_name)
    result: str = tpl_path.read_text(encoding="utf-8")
    result = result.replace("{{market_name}}", market_name)
    if is_dev:
        banner: str = (
            f"> WARNING: Development build. For stable use, install "
            f"`{config.market_name}` instead."
        )
        result = result.replace("{{is_dev_banner}}", banner)
    else:
        # Drop the placeholder line and its trailing blank line entirely.
        result = result.replace("{{is_dev_banner}}\n\n", "")
    result = result.replace("{{host}}", config.host)
    result = result.replace("{{version}}", version)
    result = result.replace("{{generated_at}}", generated_at)
    result = result.replace("{{upstream_url}}", UPSTREAM_URL)
    result = result.replace("{{upstream_commit}}", upstream_commit)
    result = result.replace("{{install_block}}", install_block)
    return result


def bash_double_quoted_value(value: str) -> str:
    """Escape a value for the simple `NAME="value"` constants in _lib/meta.sh."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def substitute_meta_constant(text: str, name: str, value: str, meta_path: Path) -> str:
    replacement: str = f'{name}="{bash_double_quoted_value(value)}"'
    text, n_subs = re.subn(
        rf"^{name}=.*$",
        lambda _match: replacement,
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if n_subs != 1:
        print(
            f"error: {meta_path}: expected exactly one {name}=... "
            f"line to substitute, found {n_subs}",
            file=sys.stderr,
        )
        sys.exit(1)
    return text


# Shared skill content (see devops Domain architecture: Shared skill content).
# Snippets live in this skill subdirectory and are referenced from sibling
# skills via the sibling-relative link form `../uspecs-concepts/shared/<name>.md`.
# At generation time those links are inlined with the snippet content and the
# shared/ source directory is excluded from the published output.
_SHARED_SKILL: str = "uspecs-concepts"
_SHARED_SUBDIR: str = "shared"

# A Markdown link whose target is `../uspecs-concepts/shared/<name>.md`,
# optionally on its own line (the only supported reference form).
_SHARED_LINK_RE: re.Pattern[str] = re.compile(
    r"\[[^\]]*\]\(\.\./"
    + re.escape(_SHARED_SKILL)
    + r"/"
    + re.escape(_SHARED_SUBDIR)
    + r"/([^)]+)\)"
)


def inline_shared_content(skills_root: Path, shared_dir: Path) -> None:
    """Inline shared snippet links in every copied skill `*.md` file.

    For each `*.md` under `skills_root`, replace links of the form
    `[...](../uspecs-concepts/shared/<name>.md)` with the content of the
    referenced snippet (read from `shared_dir`). Exit with an error if a
    referenced snippet file does not exist.
    """
    for md_path in sorted(skills_root.rglob("*.md")):
        text: str = md_path.read_text(encoding="utf-8")

        def _replace(match: re.Match[str]) -> str:
            name: str = match.group(1)
            snippet: Path = shared_dir / name
            if not snippet.is_file():
                print(
                    f"error: {md_path}: shared snippet not found: {snippet}",
                    file=sys.stderr,
                )
                sys.exit(1)
            return snippet.read_text(encoding="utf-8").rstrip("\n")

        new_text: str = _SHARED_LINK_RE.sub(_replace, text)
        if new_text != text:
            md_path.write_text(new_text, encoding="utf-8")


def main() -> None:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="Generate a uspecs marketplace.",
    )
    parser.add_argument("--agent", required=True, choices=AGENT_CONFIGS.keys())
    parser.add_argument(
        "--uspecs-repo", required=True, help="Path to uspecs source repo"
    )
    parser.add_argument(
        "--marketplace-repo", required=True, help="Path to output marketplace repo"
    )
    parser.add_argument("--version", required=True, help="Version string")
    args: argparse.Namespace = parser.parse_args()

    config: AgentConfig = AGENT_CONFIGS[args.agent]
    source: Path = Path(args.uspecs_repo).resolve()
    output: Path = Path(args.marketplace_repo).resolve()

    # Validate the destructive arg first to fail fast on unsafe wipe targets.
    validate_marketplace_repo(output)

    if not source.is_dir():
        print(f"error: --uspecs-repo directory not found: {source}", file=sys.stderr)
        sys.exit(1)

    version: str = args.version
    market_name, plugin_name = resolve_names(config, version)
    upstream_commit: str = get_upstream_commit(source)
    generated_at: str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Drop everything in --marketplace-repo except .git (already validated above).
    # Fail fast and loud if any entry cannot be removed (locked file, permissions, ...).
    output.mkdir(parents=True, exist_ok=True)
    for child in output.iterdir():
        if child.name == ".git":
            continue
        try:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
        except OSError as e:
            print(
                f"error: could not remove {child}: {e}",
                file=sys.stderr,
            )
            sys.exit(1)

    plugin_dir: Path = output / plugin_name
    plugin_dir.mkdir()
    root_claude: Path = output / ".claude-plugin"
    readme_path: Path = output / "README.md"

    # Copy LICENSE from --uspecs-repo
    license_src: Path = source / "LICENSE"
    if not license_src.is_file():
        print(
            f"error: LICENSE not found in --uspecs-repo: {license_src}",
            file=sys.stderr,
        )
        sys.exit(1)
    shutil.copy2(license_src, output / "LICENSE")

    # Copy bin/
    shutil.copytree(source / "bin", plugin_dir / "bin")

    # Substitute generated uversion constants in the copied _lib/meta.sh.
    meta_path: Path = plugin_dir / "bin" / "_lib" / "meta.sh"
    meta_text: str = meta_path.read_text(encoding="utf-8")
    stream: str = "development" if is_dev_version(version) else "stable"
    substitutions: dict[str, str] = {
        "USPECS_VERSION": version,
        "USPECS_MARKETPLACE_REPO": f"uspecs/{market_name}",
        "USPECS_MARKETPLACE_NAME": market_name,
        "USPECS_STREAM": stream,
        "USPECS_CLI": config.cli,
        "USPECS_MARKETPLACE_UPDATE_VERB": config.marketplace_update_verb,
    }
    for name, value in substitutions.items():
        meta_text = substitute_meta_constant(meta_text, name, value, meta_path)
    meta_path.write_text(meta_text, encoding="utf-8")

    # Guard against stale metadata from source or previous generated output.
    stale_market_metadata: Path = plugin_dir / "bin" / "uspecs-market.json"
    if stale_market_metadata.exists():
        stale_market_metadata.unlink()

    # Copy knowledge skills (uspecs-* only, from .claude/skills/)
    src_skills: Path = source / ".claude" / "skills"

    # Validate knowledge skill frontmatter at source
    validate_skill_frontmatter(src_skills)

    dst_skills: Path = plugin_dir / "skills"
    dst_skills.mkdir()
    for skill_dir in sorted(src_skills.iterdir()):
        if skill_dir.is_dir() and skill_dir.name.startswith("uspecs-"):
            shutil.copytree(skill_dir, dst_skills / skill_dir.name)

    # Inline shared skill content, then drop the shared/ source from output.
    shared_src: Path = src_skills / _SHARED_SKILL / _SHARED_SUBDIR
    inline_shared_content(dst_skills, shared_src)
    shared_dst: Path = dst_skills / _SHARED_SKILL / _SHARED_SUBDIR
    if shared_dst.is_dir():
        shutil.rmtree(shared_dst)

    # Load template and actions
    tpl_path: Path = TEMPLATES_DIR / config.action_template
    template_text: str = tpl_path.read_text(encoding="utf-8")
    actions: list[ActionData] = load_actions(source)

    commands_dir: str | None = None
    if config.output_kind == "commands":
        # Claude: generate commands/<action>.md
        commands_dir = "commands"
        cmd_dir: Path = plugin_dir / commands_dir
        cmd_dir.mkdir()
        for action in actions:
            dispatch: str = render_dispatch(config.dispatch, action.action)
            content: str = render_action_file(template_text, action, dispatch)
            (cmd_dir / f"{action.action}.md").write_text(content, encoding="utf-8")
    else:
        # Augment/Codex: generate skills/<action>/SKILL.md
        for action in actions:
            dispatch = render_dispatch(config.dispatch, action.action)
            content = render_action_file(template_text, action, dispatch)
            action_skill_dir: Path = dst_skills / action.action
            action_skill_dir.mkdir(exist_ok=True)
            (action_skill_dir / "SKILL.md").write_text(content, encoding="utf-8")

    # Generate .claude-plugin/marketplace.json (at repo root)
    root_claude.mkdir()
    manifest: str = render_marketplace(config, version, plugin_name)
    (root_claude / "marketplace.json").write_text(manifest, encoding="utf-8")

    # Generate plugin.json inside the plugin directory
    plugin_claude_dir: Path = plugin_dir / ".claude-plugin"
    plugin_claude_dir.mkdir()
    plugin_json: str = render_plugin_json(version, plugin_name)
    (plugin_claude_dir / "plugin.json").write_text(plugin_json, encoding="utf-8")

    # Generate README.md at repo root
    readme: str = render_readme(
        config, version, market_name, plugin_name, upstream_commit, generated_at
    )
    readme_path.write_text(readme, encoding="utf-8")

    print(f"Generated {market_name} at {output}")


if __name__ == "__main__":
    main()
